// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfdvgnrrbttjpivqwugd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mZHZnbnJyYnR0anBpdnF3dWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTc4MzEsImV4cCI6MjA3MTM5MzgzMX0.-ZE-qaiOupEdMaCPuvlsXYI2prh8a9V_6JMyYMDuUDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});